version: "3.8"
services:
  loadbalancer:
    build:
      context: ./Loadbalancer
    depends_on: 
      - service1
      - service2
      - service3
    restart: always
    ports: 
      - "8080:8080"
    container_name: loadbalancer
    networks:
      - tracking-system-network
  accountsdb:
    build:
      context: ./Postgres
    restart: always
    command: postgres -c 'max_connections=256'
    environment: 
      POSTGRES_PASSWORD: NgR7151Yt2nH
      POSTGRES_USER: trackinguser
      POSTGRES_DB: tracking
    volumes: 
      - ./Postgres/data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    container_name: accountsdb
    networks:
      - tracking-system-network
  service1:
    build:
      context: ./TrackingService
    depends_on: 
      - accountsdb
    ports:
      - "7001:7000"
    container_name: service1
    networks:
      - tracking-system-network
  service2:
    build:
      context: ./TrackingService
    depends_on: 
      - accountsdb
    ports:
      - "7002:7000"
    container_name: service2
    networks:
      - tracking-system-network
  service3:
    build:
      context: ./TrackingService
    depends_on: 
      - accountsdb
    ports:
      - "7003:7000"
    container_name: service3
    networks:
      - tracking-system-network
  pubsub:
    build:
      context: ./PubSub
    ports:
      - "7070:7070"
    container_name: pubsub
    networks:
      - tracking-system-network
  cli1:
    build:
      context: ./Cli
    container_name: cli1
    networks:
      - tracking-system-network
networks:
  tracking-system-network:
    name: tracking-system-network